spring:
  application:
    name: "Nexus ML Integrator"
    profile: "production"

endpoints:
  base-url-ml: "https://api.mercadolibre.com"
  base-url-mp: "https://api.mercadopago.com"
  get:
    payment: "/v1/payments/%d"
  post:
    oauth-token: "/oauth/token"